export const siteTaskDefinitions = [
  {
    key: 'listing',
    label: 'Module One',
    route: '/listing',
    description: 'Structured records with expanded detail fields.',
    contentType: 'listing',
    enabled: true,
  },
  {
  key: 'classified',
  label: 'Module Two',
  route: '/classified',
  description: 'Fast-moving short-form entries.',
  contentType: 'classified',
  enabled: true,
},
  {
    key: 'article',
    label: 'Module Three',
    route: '/article',
    description: 'Long-form notes and context.',
    contentType: 'article',
    enabled: true,
  },
  {
    key: 'image',
    label: 'Module Four',
    route: '/image',
    description: 'Media-focused cards and previews.',
    contentType: 'image',
    enabled: true,
  },
  {
    key: 'profile',
    label: 'Module Five',
    route: '/profile',
    description: 'Identity surfaces and linked contributors.',
    contentType: 'profile',
    enabled: true,
  },
  {
    key: 'sbm',
    label: 'Module Six',
    route: '/sbm',
    description: 'Collections and saved references.',
    contentType: 'sbm',
    enabled: true,
  },
  {
    key: 'comment',
    label: 'Module Seven',
    route: '/blog',
    description: 'Response stream and discussion notes.',
    contentType: 'comment',
    enabled: false,
  },
  {
    key: 'pdf',
    label: 'Module Eight',
    route: '/pdf',
    description: 'Document and file resources.',
    contentType: 'pdf',
    enabled: true,
  },
  {
    key: 'org',
    label: 'Module Nine',
    route: '/team',
    description: 'Entity pages and grouped records.',
    contentType: 'org',
    enabled: true,
  },
] as const

export const siteTaskViews = {
  listing: '/listing',
  classified: '/classified',
  article: '/article',
  image: '/image',
  profile: '/profile',
  social: '/community',
  sbm: '/sbm',
  comment: '/blog',
  pdf: '/pdf',
  org: '/team',
} as const
